### ISSUE TITLE
Hostname mandatory field ?

### ISSUE THREAD

**Issue by g-arjuna** [automateyournetwork/business_ready#25]
Hey John,

Just trying to understand why is the hostname made a mandatory field. I am trying to map a set of devices for their mac address table. but i would not be knowing the hostname for each one of them . i want to call your function multiple times and collect json . But it is really impossible to do that if hostname is a mandatory field. Can you let me know why?

**Comment by automateyournetwork** [comment]
Hello!

I can adjust it to not require the hostname but I need a few days

Thanks

John

**Comment by jhinckley** [comment]
Hi John!

Did you ever make the adjustment to the hostname requirement?

Thanks, 
John

**Comment by automateyournetwork** [comment]
Added learn hostname = true you should be able to use IP addresses now! Thanks for opening the issue

**Comment by automateyournetwork** [comment]
Ah ! Sorry!

I just patched it - let me know if it works you should be able to use IP
addresses now

Thanks happy holidays

John

**Comment by g-arjuna** [comment]
Thanks John . Just saw your tweet. Will check and let you know!
